theme = "everforest_light"

[editor]
bufferline = "multiple"
color-modes = true
completion-replace = true
line-number = "relative"
mouse = false
rulers = [119]
undercurl = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "diagnostics"] #, "file-modification-indicator", "version-control"]
center = ["file-name"] # file-base-name"]
right = ["spinner", "file-type", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
skip-levels = 1
character = "▏"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
'}' = 'goto_next_paragraph'
'{' = 'goto_prev_paragraph'

[keys.normal.space]
F = 'file_picker_in_current_buffer_directory'

[keys.normal.";"]
";" = "collapse_selection"
j = ":buffer-next"
k = ":buffer-previous"
J = "goto_next_diag"
K = "goto_prev_diag"
space = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''']
's' = [''':sh tmux send-keys Q/# Space %% Enter O# Escape Escape Nvg.a BSpace BSpace Escape Escape '\;' Space uuQ''']
